Arte\PCMS\BizlogicBundle\Entity\TBDepartment:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            nullable: false
        SortNo:
            type: integer
            nullable: false
        DeleteFlag:
            type: boolean
            nullable: true
        CreatedUserId:
            type: integer
            nullable: true
        CreatedDatetime:
            type: datetime
            nullable: true
        UpdatedUserId:
            type: integer
            nullable: true
        UpdatedDatetime:
            type: datetime
            nullable: true
    oneToMany:
        TBSystemUsersDepartmentId:
            targetEntity: TBSystemUser
            mappedBy: TBDepartmentDepartmentId
    manyToOne:
        TBSystemUserUpdatedUserId:
            targetEntity: TBSystemUser
            inversedBy: TBDepartmentsUpdatedUserId
            joinColumns:
                UpdatedUserId:
                    referencedColumnName: id
        TBSystemUserCreatedUserId:
            targetEntity: TBSystemUser
            inversedBy: TBDepartmentsCreatedUserId
            joinColumns:
                CreatedUserId:
                    referencedColumnName: id
    manyToMany: {  }
