Arte\PCMS\BizlogicBundle\Entity\TBProjectCostMaster:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ProjectMasterId:
            type: integer
            nullable: false
        Name:
            type: string
            length: 255
            nullable: false
        Cost:
            type: integer
            nullable: true
        SortNo:
            type: integer
            nullable: true
        DeleteFlag:
            type: boolean
            nullable: true
        HierarchyPath:
            type: string
            length: 255
            nullable: true
    oneToMany:
        TBProductionCostsProjectCostMasterId:
            targetEntity: TBProductionCost
            mappedBy: TBProjectCostMasterProjectCostMasterId
    manyToOne:
        TBProjectMasterProjectMasterId:
            targetEntity: TBProjectMaster
            inversedBy: TBProjectCostMastersProjectMasterId
            joinColumns:
                ProjectMasterId:
                    referencedColumnName: id
    manyToMany: {  }
