Arte\PCMS\BizlogicBundle\Entity\TBProjectMaster:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            nullable: false
        Status:
            type: integer
            nullable: false
        Explanation:
            type: string
            length: 255
            nullable: true
        CustomerId:
            type: integer
            nullable: false
        DeleteFlag:
            type: boolean
            nullable: true
    oneToMany:
        TBProjectUsersProjectMasterId:
            targetEntity: TBProjectUser
            mappedBy: TBProjectMasterProjectMasterId
        TBProjectCostMastersProjectMasterId:
            targetEntity: TBProjectCostMaster
            mappedBy: TBProjectMasterProjectMasterId
    manyToOne:
        TBCustomerCustomerId:
            targetEntity: TBCustomer
            inversedBy: TBProjectMastersCustomerId
            joinColumns:
                CustomerId:
                    referencedColumnName: id
    manyToMany: {  }
