Arte\PCMS\BizlogicBundle\Entity\TBProjectMaster:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            nullable: false
        Status:
            type: integer
            nullable: false
        Explanation:
            type: string
            length: 255
            nullable: true
        CustomerId:
            type: integer
            nullable: false
        DeleteFlag:
            type: boolean
            nullable: true
        PeriodStart:
            type: date
            nullable: true
        PeriodEnd:
            type: date
            nullable: true
        ManagerId:
            type: integer
            nullable: true
        EstimateFilePath:
            type: string
            nullable: true
        ScheduleFilePath:
            type: string
            nullable: true
    oneToMany:
        TBProjectUsersProjectMasterId:
            targetEntity: TBProjectUser
            mappedBy: TBProjectMasterProjectMasterId
        TBProjectCostMastersProjectMasterId:
            targetEntity: TBProjectCostMaster
            mappedBy: TBProjectMasterProjectMasterId
        TBProjectCostHierarchyMastersTBProjectMasterId:
            targetEntity: TBProjectCostHierarchyMaster
            mappedBy: TBProjectMasterTBProjectMasterId
    manyToOne:
        TBCustomerCustomerId:
            targetEntity: TBCustomer
            inversedBy: TBProjectMastersCustomerId
            joinColumns:
                CustomerId:
                    referencedColumnName: id
        TBSystemUserManagerId:
            targetEntity: TBSystemUser
            inversedBy: TBProjectMastersManagerId
            joinColumns:
                ManagerId:
                    referencedColumnName: id
    manyToMany: {  }
