Arte\PCMS\BizlogicBundle\Entity\TBSystemUser:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        LoginId:
            type: string
            length: 40
            nullable: false
        Salt:
            type: string
            length: 40
            nullable: false
        Password:
            type: string
            length: 40
            nullable: false
        Active:
            type: boolean
            nullable: false
        SystemRoleId:
            type: integer
            nullable: true
        DisplayName:
            type: string
            length: 50
            nullable: false
        DisplayNameKana:
            type: string
            length: 50
            nullable: false
        NickName:
            type: string
            length: 50
            nullable: false
        MailAddress:
            type: string
            length: 100
            nullable: false
        DepartmentId:
            type: integer
            nullable: true
        LastLoginDatetime:
            type: datetime
            nullable: true
        DeleteFlag:
            type: boolean
            nullable: true
    oneToMany:
        TBProjectUsersSystemUserId:
            targetEntity: TBProjectUser
            mappedBy: TBSystemUserSystemUserId
    manyToOne:
        TBDepartmentDepartmentId:
            targetEntity: TBDepartment
            inversedBy: TBSystemUsersDepartmentId
            joinColumns:
                DepartmentId:
                    referencedColumnName: id
    manyToMany: {  }
