security:
    encoders:
        Arte\PCMS\BizlogicBundle\Entity\TBSystemUser: plaintext
#        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_users:
#            entity: { class: Arte\PCMS\BizlogicBundle\Entity\TBSystemUser, property: Username }
            entity: { class: Arte\PCMS\BizlogicBundle\Entity\TBSystemUser }
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
#            pattern:    ^/
            pattern:    ^/demo/
            form_login:
                check_path: auth_login_check
                login_path: auth_login
            logout:
                path:   auth_logout
                target: auth_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # /testにはROLE_USERとROLE_ADMINがアクセス可能
        - { path: ^/, roles: ROLE_USER }
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
