Arte\PCMS\PublicBundle\Entity\TBDepartment:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            nullable: false
        SortNo:
            type: integer
            nullable: false
        DeleteFlag:
            type: boolean
            nullable: true
    oneToMany:
        TBSystemUsersDepartmentId:
            targetEntity: TBSystemUser
            mappedBy: TBDepartmentDepartmentId
    manyToOne: {  }
    manyToMany: {  }
