Arte\PCMS\PublicBundle\Entity\TBProductionCost:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ProjectCostMasterId:
            type: integer
            nullable: false
        SystemUserId:
            type: integer
            nullable: false
        WorkDate:
            type: date
            nullable: false
        Cost:
            type: integer
            nullable: false
        Note:
            type: text
            nullable: true
        DeleteFlag:
            type: boolean
            nullable: false
    oneToMany: {  }
    manyToOne:
        TBProjectCostMasterProjectCostMasterId:
            targetEntity: TBProjectCostMaster
            inversedBy: TBProductionCostsProjectCostMasterId
            joinColumns:
                ProjectCostMasterId:
                    referencedColumnName: id
        TBSystemUserSystemUserId:
            targetEntity: TBSystemUser
            inversedBy: TBProductionCostsSystemUserId
            joinColumns:
                SystemUserId:
                    referencedColumnName: id
    manyToMany: {  }
