Arte\PCMS\PublicBundle\Entity\VProjectUser:
    type: entity
    indexes: {  }
    id:
        SystemUserId:
            type: integer
        ProjectMasterId:
            type: integer
    fields:
        RoleNo:
            type: integer
            nullable: false
    oneToMany: {  }
    manyToOne:
        TBSystemUserSystemUserId:
            targetEntity: TBSystemUser
            inversedBy: VProjectUsersSystemUserId
            joinColumns:
                SystemUserId:
                    referencedColumnName: id
        VProjectViewProjectMasterId:
            targetEntity: VProjectView
            inversedBy: VProjectUsersProjectMasterId
            joinColumns:
                ProjectMasterId:
                    referencedColumnName: id
    manyToMany: {  }
Arte\PCMS\BizlogicBundle\Entity\VProjectUser:
    type: mappedSuperclass
    readOnly: true
